version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - project-one-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - initiatives
  app: &app
    container_name: app
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    networks:
      - initiatives
  sneakers:
    <<: *app  
    container_name: sneakers
    command: ['rake', 'sneakers:run']
    ports:
      - "3001:3000"
    networks:
      - initiatives
volumes:
  rubygems:
  project-one-data:
  
networks:
  initiatives:
    external: true